services:
  app:
    image: ${APP_IMAGE:-dalvaes/gestion-despacho:latest}
    container_name: gestion-despacho
    ports: ["8080:8080"]
    volumes:
      - /mnt/efs:/app/efs
    environment:
      APP_EFS_DIR: ${APP_EFS_DIR:-/app/efs}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID:-}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID:-}
      AZURE_B2C_USER_FLOW: ${AZURE_B2C_USER_FLOW:-B2C_1_signupsignin}
      AZURE_ISSUER_URI: ${AZURE_ISSUER_URI:-}
    restart: unless-stopped
