spring.application.name=gestion-despacho
server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:guias;DB_CLOSE_DELAY=-1}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.h2.console.enabled=false
app.efs.dir=${APP_EFS_DIR:/app/efs}
spring.rabbitmq.host=${RABBITMQ_HOST:${SPRING_RABBITMQ_HOST:localhost}}
spring.rabbitmq.port=${RABBITMQ_PORT:${SPRING_RABBITMQ_PORT:5672}}
spring.rabbitmq.username=${RABBITMQ_USER:${SPRING_RABBITMQ_USERNAME:guest}}
spring.rabbitmq.password=${RABBITMQ_PASS:${SPRING_RABBITMQ_PASSWORD:guest}}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
app.rabbitmq.exchange=${RABBITMQ_EXCHANGE:guias.exchange}
app.rabbitmq.queue.guias=${RABBITMQ_QUEUE_GUIAS:guias.queue}
app.rabbitmq.queue.errores=${RABBITMQ_QUEUE_ERRORES:guias.errores.queue}
app.rabbitmq.routingkey.guias=${RABBITMQ_ROUTINGKEY_GUIAS:guias.routingkey}
app.rabbitmq.routingkey.errores=${RABBITMQ_ROUTINGKEY_ERRORES:guias.dlq}
aws.s3.region=${AWS_REGION:us-east-1}
aws.s3.bucket=${AWS_S3_BUCKET:}
aws.accessKeyId=${AWS_ACCESS_KEY_ID:}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY:}
aws.sessionToken=${AWS_SESSION_TOKEN:}
springdoc.swagger-ui.path=/swagger-ui.html
app.azure.jwk-set-uri=${AZURE_JWK_SET_URI:}
app.azure.roles-claim=${AZURE_ROLES_CLAIM:roles}
app.azure.issuer-uri=${AZURE_ISSUER_URI:}
app.azure.audience=${AZURE_CLIENT_ID:}
