spring.application.name=gestion-despacho
server.port=8080
spring.rabbitmq.host=${RABBITMQ_HOST:${SPRING_RABBITMQ_HOST:localhost}}
spring.rabbitmq.port=${RABBITMQ_PORT:${SPRING_RABBITMQ_PORT:5672}}
spring.rabbitmq.username=${RABBITMQ_USER:${SPRING_RABBITMQ_USERNAME:guest}}
spring.rabbitmq.password=${RABBITMQ_PASS:${SPRING_RABBITMQ_PASSWORD:guest}}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
app.rabbitmq.confirm-timeout=${RABBITMQ_CONFIRM_TIMEOUT:5s}
app.rabbitmq.exchange=${RABBITMQ_EXCHANGE:guias.exchange}
app.rabbitmq.queue.guias=${RABBITMQ_QUEUE_GUIAS:guias.queue}
app.rabbitmq.queue.errores=${RABBITMQ_QUEUE_ERRORES:guias.errores.queue}
app.rabbitmq.routingkey.guias=${RABBITMQ_ROUTINGKEY_GUIAS:guias.routingkey}
app.rabbitmq.routingkey.errores=${RABBITMQ_ROUTINGKEY_ERRORES:guias.dlq}
springdoc.swagger-ui.path=/swagger-ui.html
app.azure.jwk-set-uri=${AZURE_JWK_SET_URI:}
app.azure.roles-claim=${AZURE_ROLES_CLAIM:roles}
app.azure.issuer-uri=${AZURE_ISSUER_URI:}
app.azure.audience=${AZURE_CLIENT_ID:}
