spring.application.name=gestion-despacho
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:guias;DB_CLOSE_DELAY=-1}
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.h2.console.enabled=true

app.efs.dir=${APP_EFS_DIR:/app/efs}

aws.s3.region=${AWS_REGION:us-east-1}
aws.s3.bucket=${AWS_S3_BUCKET:}
aws.accessKeyId=${AWS_ACCESS_KEY_ID:}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY:}
aws.sessionToken=${AWS_SESSION_TOKEN:}

springdoc.swagger-ui.path=/swagger-ui.html

# -------------------------------------------------------
# Azure AD B2C - OAuth2 Resource Server
# -------------------------------------------------------
azure.b2c.tenant-id=${AZURE_TENANT_ID:}
azure.b2c.user-flow=${AZURE_B2C_USER_FLOW:B2C_1_signupsignin}
azure.b2c.client-id=${AZURE_CLIENT_ID:}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AZURE_JWK_SET_URI:}